kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: authors
  labels:
    app: authors
#    project: booksapp
#    app.kubernetes.io/part-of: booksapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authors
      project: booksapp
  template:
    metadata:
      labels:
        app: authors
        project: booksapp
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/booksapp:v0.0.3
        env:
        - name: DATABASE_URL
          value: sqlite3:db/db.sqlite3
        - name: BOOKS_SITE
          value: http://books:7002
        - name: FAILURE_RATE
          value: "0.5"
        args: ["prod:authors"]
        readinessProbe:
          httpGet:
            path: /ping
            port: 7001
        ports:
        - name: service
          containerPort: 7001

