apiVersion: v1
kind: Service
metadata:
  name: authors
  labels:
    app: authors
    project: booksapp
spec:
  selector:
    app: authors
  clusterIP: None
  ports:
  - name: service
    port: 7001

