apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: webapp-ingress
spec:
  rules:
    - host: www.example.com
    - http:
        paths:
          - backend:
              serviceName: webapp
              servicePort: 7000
            path: /

