apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    project: booksapp
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
  {{- range untilStep ( int .Values.ports.start ) ( int .Values.ports.end ) 1 }}
  - name: service{{ . }}
    port: {{ . }}
  {{- end }}

