kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: traffic
  labels:
    app: traffic
#    project: booksapp
#    app.kubernetes.io/part-of: booksapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
      project: booksapp
  template:
    metadata:
      labels:
        app: traffic
        project: booksapp
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: traffic
        image: buoyantio/booksapp-traffic:v0.0.3
        args:
        - "-initial-delay=30s"
        - "webapp:7000"

